### PR TITLE
Some mods to your code

### PR DESCRIPTION
**Pull request by IU5HKU**
Hi Alexey, please have a look to this contribute to your useful code:
- new fields retrieved from open-meteo API website:
- sunrise & sunset
- UVI and expected rain
- maximum wind force, direction and gusts expected for the day in knots (sorry, i'm used to this unit a lot)
- modified forecast pages to include rain probability percentage

Hope this can be appreciated, thanks for the code!
 Marco

### CODE REVIEW

**Comment by AlexeyMal** [comment]
Hi Marco,
thank you for contributing! Looks very impressive!
I am happy that you find my code usefull and develop it to suite your needs.
True, I have only implemented the data fields I needed so far. The API offers much more.
I will check your modifications and merge them as soon as I can.
Best regards,
Alexey

**Comment by AlexeyMal** [comment]
Dear Marco,
sorry, it looks like you have not pushed the right cpp file "OpenMeteoOneCall.cpp" but a copy of the header. 
In your push request the files "OpenMeteoOneCall.cpp" and "OpenMeteoOneCall.h" are identical.
Please push the right  "OpenMeteoOneCall.cpp" file.
Thank you!
Best regards,
Alexey

**Comment by IU5HKU** [comment]
Sorry Alexey, i think i'm becoming old... :-\ i did a stupid cut&paste error, have a look, hope the files are the right ones now
Feel free to contact me for every other possible problem, have a nice day!!
 Marco

**Comment by IU5HKU** [comment]
Thank you Alexey :-)

**Pull request merged**
